src/DOLOST/blueprints/api.py
from flask import Blueprint, request, jsonify, Response, url_for
from functools import wraps
from ..services.docker_manager import DockerManager
from ..services.logger import DolostLogger
import os, json

from ..context import Context

# Construct the path to dockerfiles_templates
dockerfiles_path = os.path.join(Context.base_dir, 'dockerfiles_templates')

api_blueprint = Blueprint('api', __name__)

docker_manager = DockerManager.get_instance()
logger = DolostLogger.get_instance()

# Decorator for error handling
def error_handling(func):
    """
    Decorator for error handling.

    Args:
        func (function): The function to be decorated.

    Returns:
        function: The wrapper function for error handling.
    """
    @wraps(func)
    def wrapper(*args, **kwargs):
        try:
            return func(*args, **kwargs)
        except Exception as e:
            logger.error(f'Error during operation: {str(e)}')
            raise
            return jsonify({"status": "error", "message": str(e)}), 500
    wrapper.__name__ = func.__name__
    return wrapper

# Load existing operations from the JSON file
def load_operations_db():
    """
    Load existing operations from the JSON file.

    Returns:
        list: A list containing operations data loaded from the JSON file.
    """
    try:
        with open('operationsdb.json', 'r') as f:
            operations = json.load(f)
    except FileNotFoundError:
        operations = []
    return operations

# Update the JSON file with modified operations data
def update_operations_db(data):
    """
    Update the JSON file with modified operations data.

    Args:
        data (list): The modified operations data to be written to the JSON file.
    """
    with open('operationsdb.json', 'w') as f:
        json.dump(data, f, indent=4)

# Update an operation based on it's ID
def update_operation_entry(operation_id, new_operation_content, update_decoys:bool=False):
    """
    Update an operation based on its ID.

    Args:
        operation_id (int): The ID of the operation to be updated.
        new_operation_content (dict): The new content for the operation.
        update_decoys (bool, optional): Whether to update decoys data. Defaults to False.
    """
    operations = load_operations_db()
    for operation in operations:
        if operation.get('id') == operation_id:
            # Update the operation content
            for key, value in new_operation_content.items():
                operation[key] = value
            # Update the decoys if update_decoys is True
            if update_decoys:
                operation['decoys'] = new_operation_content.get('decoys', operation.get('decoys', []))
            break
    update_operations_db(operations)

# Modify the operations's decoys 
def update_operation_decoys(operation_id, decoy):
    """
    Modify the operation's decoys.

    Args:
        operation_id (int): The ID of the operation.
        decoy (dict): Decoy information to be added to the operation.
    """
    operations_data = load_operations_db()

    operation = find_operation_by_id(operation_id)

    # Ensure that the "decoys" key holds a list
    if "decoys" not in operation or not isinstance(operation["decoys"], list):
        operation["decoys"] = []
    
    # Filter out any additional fields that are not needed for decoys
    required_decoy_keys = ["Hostname", "Description", "IP", "Subnet", "Gateway", "DeceptionNetwork", "ServicePorts", "Service", "DecoyFiles"]
    filtered_decoys = {key: decoy.get(key) for key in required_decoy_keys}

    # Append the new operation decoys
    operation["decoys"].append(filtered_decoys)
    
    # Write the updated decoys into the file
    return update_operation_entry(operation_id, operation, update_decoys=True)

# Generate ID for new operation based on the last ID in the JSON file
def generate_new_id(operations):
    """
    Generate ID for a new operation based on the last ID in the JSON file.

    Args:
        operations (list): List of existing operations.

    Returns:
        int: The ID for the new operation.
    """
    if not operations:
        return 1
    else:
        # We may need to implement a fail-safe approach
        return operations[-1]['id'] + 1

# Get operation from DB using id
def find_operation_by_id(operation_id):
    """
    Get an operation from the database using its ID.

    Args:
        operation_id (int): The ID of the operation to find.

    Returns:
        dict: The operation data if found, otherwise None.
    """
    operations = load_operations_db()
    for operation in operations:
        if operation.get('id') == operation_id:
            return operation
    return None  # Return None if no operation with the given id is found

# Create a new operation
@api_blueprint.route('/operations/new', methods=['POST'])
@error_handling
def new_operation():
    """
    Create a new operation.

    This endpoint allows the creation of a new operation. It expects a POST request with JSON data containing the necessary information for the new operation.

    Returns:
        jsonify: JSON response indicating the status of the operation creation.
            - status (str): Status of the operation creation ("OK" or "error").
            - message (str): Additional message providing details about the status.
            - redirect (str, optional): URL to redirect the client to upon successful operation creation.

    Raises:
        BadRequest: If the request data is invalid or missing required fields.
    """
    try:
        required_keys = {
            'preparation': ['name', 'objective', 'assets'],
            'narrative': ['storytelling', 'deception_activities', 'monitoring'],
            'closure_criteria': ['limits', 'end_date', 'commander'],
        }

        data = request.get_json()

        # Filter out any additional fields that are not in the required keys
        filtered_data = {}
        for section, keys in required_keys.items():
            if section in data:
                filtered_data[section] = {key: data[section][key] for key in keys if key in data[section]}
            else:
                filtered_data[section] = {}

        # Check if all required keys are present in the filtered data for each section
        missing_keys = []
        for section, keys in required_keys.items():
            missing_keys.extend([f"Missing key '{key}' in section '{section}'" for key in keys if key not in filtered_data[section]])

        if missing_keys:
            return jsonify({"status": "error", "message": "\n".join(missing_keys)}), 400

        # Check if the 'preparation' section is present and 'name' field is not empty
        if not filtered_data['preparation'].get('name'):
            return jsonify({"status": "error", "message": "The 'Operation Name' field under 'Preparation' section cannot be empty"}), 400

        # Check if decoys are provided and filter out any additional keys
        if 'decoys' in data:
            decoys = data['decoys']
            filtered_decoys = []
            for decoy in decoys:
                # Check if all required decoy keys are present
                required_decoy_keys = ["Hostname", "Description", "IP", "Subnet", "Gateway", "DeceptionNetwork", "ServicePorts", "Service", "DecoyFiles"]
                missing_decoy_keys = [key for key in required_decoy_keys if key not in decoy]
                if missing_decoy_keys:
                    return jsonify({"status": "error", "message": f"Missing key(s) {', '.join(missing_decoy_keys)} in decoy"}), 400
                filtered_decoys.append({key: decoy[key] for key in required_decoy_keys})
            filtered_data['decoys'] = filtered_decoys

        new_operation = filtered_data
        actual_operations = load_operations_db()
        
        # Generate ID for the new operation
        new_id = generate_new_id(actual_operations)
        
        # Add the new operation data to the list with the generated ID
        new_operation['id'] = new_id
        actual_operations.append(new_operation)
        update_operations_db(actual_operations)
        
        return jsonify({"status": "OK", "redirect": url_for('views.view_operation', operation_id=new_id)})
    
    except Exception as e:
        return jsonify({"status": "error", "message": str(e)}), 400

# Edit an operation
@api_blueprint.route('/operations/<int:operation_id>/edit', methods=['POST'])
@error_handling
def edit_operation(operation_id):
    """
    Edit an existing operation.

    Args:
        operation_id (int): The ID of the operation to edit.

    Returns:
        jsonify: JSON response indicating the status of the operation editing.
    """
    try:
        required_keys = {
            'preparation': ['name', 'objective', 'assets'],
            'narrative': ['storytelling', 'deception_activities', 'monitoring'],
            'closure_criteria': ['limits', 'end_date', 'commander'],
        }

        data = request.get_json()

        # Filter out any additional fields that are not in the required keys
        filtered_data = {}
        for section, keys in required_keys.items():
            if section in data:
                filtered_data[section] = {key: data[section][key] for key in keys if key in data[section]}
            else:
                filtered_data[section] = {}

        # Check if all required keys are present in the filtered data for each section
        missing_keys = []
        for section, keys in required_keys.items():
            missing_keys.extend([f"Missing key '{key}' in section '{section}'" for key in keys if key not in filtered_data[section]])

        if missing_keys:
            return jsonify({"status": "error", "message": "\n".join(missing_keys)}), 400

        # Check if the 'preparation' section is present and 'name' field is not empty
        if not filtered_data['preparation'].get('name'):

src/DOLOST/templates/docker_client_config.html
{% extends 'base.html' %}

{% block title %} Docker Client Configuration {% endblock %}

{% block extra_head %}
<script type="text/javascript" src="{{url_for('static', filename='js/docker_config_worker.js')}}"></script>
{% endblock %}

{% block content %}
<div class="container rounded-4 p-4 bg-light col-6" id="content">
	<div class="row align-items-center">
		<div class="col">
			<span class="d-inline-block" data-bs-placement="bottom" data-bs-toggle="tooltip" title="Edit or simply view the Decoys from a JSON or Excel file. Also save your modifications directly from here!">
				<h2>Docker Client Configuration</h2>
			</span>
		</div>
	</div>
	<div class="row mt-2">
		<div class="col">
		        <div class="mb-3">
		            <label for="configType" class="form-label">Select configuration type:</label>
		            <select id="configType" class="form-select">
		                <option value="env">From Environment Variables</option>
		                <option value="socket">From Socket</option>
		                <option value="tcp">From TCP</option>
		                <option value="tcp_ssl">From TCP with SSL</option>
		            </select>
		        </div>

		        <div id="configFields" class="mb-3">
		            <!-- Configuration fields will be inserted here based on the selected type -->
		        </div>

		        <button id="configureButton" class="btn btn-orange text-white">
		        	<i class="bi bi-gear-wide-connected"></i> Configure Docker Client
		        </button>
		</div>
	</div>
</div>
{% endblock content %}
{% block scripts %}
<script type="text/javascript" module>
	var modifyDockerClientUrl = "{{ url_for('api.modify_docker_client') }}";
    var dockerConfig = JSON.parse('{{ docker_config | tojson | safe }}');
</script>
{% endblock scripts %}

src/DOLOST/templates/operations.html
{% extends 'base.html' %}

{% block title %} Deception Operations {% endblock %}

{% macro generate_row(data) %}
    {% for item in data %}
        <tr id="row-{{ item.id }}">
            <th class="text-center col-1"><a href="{{ url_for('views.view_operation', operation_id=item.id) }}" class="text-reset text-decoration-none">{{ item.id }}</a></th>
            <td><a href="{{ url_for('views.view_operation', operation_id=item.id) }}" class="text-reset text-decoration-none">{{ item.preparation.name }}</a></td>
			<td class="text-center">{{ item.closure_criteria.commander | default("N/A") if item.closure_criteria.commander != "" else "N/A" }}</td>
			<td class="text-center">{{ item.closure_criteria.end_date | default("N/A") if item.closure_criteria.end_date != "" else "N/A" }}</td>
            <td class="text-center">
                <a href="{{ url_for('views.view_operation', operation_id=item.id) }}" type="button" class="btn btn-primary"><i class="bi bi-eye"></i></a>
                <button type="button" class="btn btn-danger delete-operation" data-operation-id="{{ item.id }}" data-bs-toggle="tooltip" title="Hold to delete"><i class="bi bi-trash"></i></button>
            </td>
        </tr>
    {% endfor %}
{% endmacro %}

{% block extra_head %}
<script src="{{ url_for('static', filename='js/operations_creator.js') }}" type="module"></script>
{% endblock %}


{% block content %}
<div class="container" id="content">
	<div class="row align-items-center">
		<div class="col">
			<span class="d-inline-block" data-bs-placement="top" data-bs-toggle="tooltip" title="View, manage and create Deception Operations">
				<h2>Deception Operations</h2>
			</span>
		</div>
		<div class="col-auto">
			<button type="button" class="btn btn-orange text-white" data-bs-toggle="modal" data-bs-target="#NewOpModal">
				<i class="bi bi-file-earmark-plus"></i> New Operation
			</button>
		</div>
	</div>
	<br>

  <div class="container">
	<div class="row">
	  <div class="col-12">
		<table class="table table-striped table-hover">
		  <thead>
			<tr>
			  <th scope="col" class="text-center">#</th>
			  <th scope="col">Operation Name </th>
			  <th scope="col" class="text-center col-2">Owner</th>
			  <th scope="col" class="text-center col-2">End Date</th>
			  <th scope="col" class="text-center col-2">Actions</th>
			</tr>
		  </thead>
		  <tbody>
			{{ generate_row(data) }}
		  </tbody>
		</table>
		
		</table>
	  </div>
	</div>
  </div>

</div>

<!-- New Operation Modal -->
<div class="modal modal-lg fade" id="NewOpModal" tabindex="-1" aria-labelledby="NewOpModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered">
	  <div class="modal-content">
		<div class="modal-header">
		  <h5 class="modal-title" id="NewOpModalLabel">New Deception Operation</h5>
		  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
		</div>
		<div class="modal-body">
		  <!-- Preparation Accordion -->
		  <div class="accordion mt-2" id="NewOpAccordion1">
			  <div class="accordion-item new-op-item">
				  <h2 class="accordion-header">
					  <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#NewOpHeading1" aria-expanded="true" aria-controls="NewOpHeading2">
							Preparation
					  </button>
				  </h2>
				  <div id="NewOpHeading1" class="accordion-collapse collapse" data-bs-parent="#NewOpAccordion1">
					  <div class="accordion-body">
						<div class="mb-3">
							<label for="name" class="form-label">Operation Name *</label>
							<input type="text" class="form-control" id="name" placeholder="Example: Dev environment protection" required>
						  </div>
						  <div class="mb-3">
							<label for="objective" class="form-label">Objective</label>
							<textarea class="form-control" id="objective" rows="2" placeholder="Example: Detect Malicius Behaviour from compromised Developer device" ></textarea>
						  </div>
						  <div class="mb-3">
							<label for="assets" class="form-label">Main Assets involved</label>
							<textarea class="form-control" id="assets" rows="3" placeholder="Example: Developer PC | Office Network | Github Repositories | Internal Dev Server | Internal DB Server" ></textarea>
						  </div>
					  </div>
				  </div>
			  </div>

		  </div>
		  <!-- / Preparation Accordion -->
		  <!-- Narrative Accordion -->
		  <div class="accordion mt-2" id="NewOpAccordion2">
			<div class="accordion-item new-op-item">
				<h2 class="accordion-header">
					<button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#NewOpHeading2" aria-expanded="true" aria-controls="NewOpHeading2">
						  Narrative
					</button>
				</h2>
				<div id="NewOpHeading2" class="accordion-collapse collapse" data-bs-parent="#NewOpAccordion2">
					<div class="accordion-body">
					  <div class="mb-3">
						  <label for="storytelling" class="form-label">Storytelling</label>
						  <textarea class="form-control" id="storytelling" rows="3" placeholder="Example: We have an old version our web app available in the network that is used for testing. | Leonardo its our external developer that is involved in some interesting projects"></textarea>
						</div>
						<div class="mb-3">
						  <label for="deception_activities" class="form-label">Deception Activities</label>
						  <textarea class="form-control" id="deception_activities" rows="3" placeholder="Example: Leonardo user created and uploaded in 25% of the Developers computers | Some curated project files from real user with Leonardo in FS that reference to a DolosT decoy | A monitored cloud key and secret key in some real document some developer computer " ></textarea>
						</div>
						<div class="mb-3">
						  <label for="monitoring" class="form-label">Monitoring</label>
						  <textarea class="form-control" id="monitoring" rows="3" placeholder="Example: Leonardo user logon and usage | Cloud token monitoring to SIEM | DolosT logs to SIEM" ></textarea>
						</div>
					</div>
				</div>
			</div>

		</div>
		<!-- / Narrative Accordion -->
		  <!--  Closure criteria Accordion -->
		  <div class="accordion mt-2" id="NewOpAccordion3">
			<div class="accordion-item new-op-item">
				<h2 class="accordion-header">
					<button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#NewOpHeading3" aria-expanded="true" aria-controls="NewOpHeading2">
						Closure criteria
					</button>
				</h2>
				<div id="NewOpHeading3" class="accordion-collapse collapse" data-bs-parent="#NewOpAccordion3">
					<div class="accordion-body">
					  <div class="mb-3">
						  <label for="limits" class="form-label">Limits</label>
						  <textarea class="form-control" id="limits" rows="3" placeholder=" "></textarea>
						</div>
						<div class="mb-3">
							<label for="end_date">End Date</label>
							<input id="end_date" class="form-control" type="date" />			
						</div>
						<div class="mb-3">
						  <label for="commander" class="form-label">Operation Commander</label>
						  <input class="form-control" id="commander" placeholder="Example: Joaquin Maldivas" ></input>
						</div>
					</div>
				</div>
			</div>

		</div>
		<!-- / Closure criteria Accordion -->
		  <!--  Decoys -->
		  <div class="accordion mt-2" id="NewOpAccordion4">
			<div class="accordion-item new-op-item">
				<h2 class="accordion-header">
					<button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#d" aria-expanded="true" aria-controls="NewOpHeading2">
						Decoys Configuration
					</button>
				</h2>
				<div id="d" class="accordion-collapse collapse m-5" data-bs-parent="#NewOpAccordion4">
					<div class="input-group">
						<input type="file" class="form-control" id="decoys" aria-describedby="LoadDecoyConfig" aria-label="Upload">
					  </div>
				</div>
			</div>

		</div>
		<!-- / Closure criteria Accordion -->

		</div>
		<div class="modal-footer">
			<button id="SaveNewOp" type="submit" class="btn btn-primary" data-bs-dismiss="modal" >Save</button>
			<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
		</div>
	  </div>
	</div>
  </div>
  <!-- / New Operation Modal -->
{% endblock %}

{% block scripts %}
<script type="text/javascript">
	var newOperationUrl = "{{ url_for('api.new_operation') }}";
	var deleteOperationUrl = "{{ url_for('api.remove_operation', operation_id='') }}";
</script>
{% endblock %}

src/DOLOST/templates/view_activity.html
{% extends 'base.html' %}

{% block title %} Activity Dashboard {% endblock %}

{% block extra_head %}
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/4.7.4/socket.io.js"></script>
<script src="{{ url_for('static', filename='js/view_activities_worker.js') }}" type="module"></script>
<style type="text/css">
    .log-line {
        color: #00FF00;
        font-family: monospace;
        margin: 0;
        padding: 2px 5px;
        white-space: pre-wrap;
    }
    .terminal-container {
        position: relative;
        background-color: #101010;
        color: #fff;
        padding: 10px;
        border-radius: 5px;
        overflow: hidden;
    }

    .terminal-content {
        max-height: 300px;
        overflow-y: auto;
        margin-top: 10px;
        font-family: monospace;
        white-space: pre-wrap;
    }
	.terminal-maximized {
	    max-height: 80vh; /* Set maximum height to 80% of the viewport height */
	}

    /* For Webkit browsers like Chrome and Safari */
    .terminal-content::-webkit-scrollbar {
        width: 8px; /* Set the width of the scrollbar */
        background-color: gray;
    }

    .terminal-content::-webkit-scrollbar-thumb {
        background: #C0C0C0;
        border-radius: 4px; /* Set the border radius of the track */
    }

</style>
{% endblock %}

{% block content %}

<div class="container" id="content">
	<div class="row align-items-center">
		<div class="col">
			<h2> Activity Dashboard </h2>
		</div>
	</div>
	<hr>
	<div class="row">
		<div class="col">
			<section class="rounded-4 bg-light p-4">
				<h3>Observables & IoCs</h3>
				<div id="IOCsCarousel" class="carousel slide p-2">
					<div class="carousel-inner">
						<div class="carousel-item active">
							<div class="row">
								<div class="col-md-3">
									<div class="card h-100 d-flex flex-column">
										<table id="ObservableUsageTable" class="table table-striped table-hover">
											<thead>
												<tr>
													<th scope="col">#</th>
													<th scope="col">Decoy usage</th>
													<th scope="col">Last 24hs Hits</th>
												</tr>
											</thead>
											<tbody>
											</tbody>
										</table>
									</div>
								</div>

								<div class="col-md-4">
									<div class="card h-100 d-flex flex-column">
										<table id="ObservableInterestingTable" class="table table-striped table-hover">
											<thead>
												<tr>
													<th scope="col">#</th>
													<th scope="col">Timestamp</th>
													<th scope="col">Decoy</th>
													<th scope="col"style="text-align:center">Observable</th>
												</tr>
											</thead>
											<tbody>
											</tbody>
										</table>
									</div>
								</div>

								<div class="col-md-5">
									<div class="card h-100 d-flex flex-column">
										<table id="ObservableIpTable" class="table table-striped table-hover">
											<thead>
												<tr>
													<th scope="col">#</th>
													<th scope="col">Timestamp</th>
													<th scope="col">Decoy</th>
													<th scope="col">IP Found</th>
												</tr>
											</thead>
											<tbody>
											</tbody>
										</table>
									</div>
								</div>

							</div>
						</div>
					</div>
				</div>
			</section>
		</div>
		<div class="container mt-4 mb-4">
			<div class="row">
				<div class="col">
					<div class="accordion" id="AcAccordion">
						<div class="accordion-item">
							<h2 class="accordion-header">
								<button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#activityDetails" aria-expanded="true" aria-controls="activityDetails">
									Raw Decoys Activity
								</button>
							</h2>
							<div id="activityDetails" class="accordion-collapse collapse show" aria-labelledby="activityDetails" data-bs-parent="#AcAccordion">
								<div class="accordion-body">
									<div class="terminal-container mt-4 mb-4">
										<div class="terminal-header d-flex justify-content-between align-items-center">
											<span class="btn btn-sm btn-danger link-unlink-button">
												<i class="bi bi-toggle-on h6"></i>
											</span>
											<span class="text-center flex-grow-1 fw-bold">Raw Decoys Activity</span>
											<div class="btn-group" role="group">
												<button type="button" class="btn btn-sm btn-secondary minimize-button" data-bs-toggle="collapse" data-bs-target="#activityDetails">
													<i class="bi bi-dash-lg"></i>
												</button>
												<button type="button" class="btn btn-sm btn-secondary maximize-button">
													<i class="bi bi-arrows-fullscreen"></i>
												</button>
											</div>
										</div>
										<div id="logList" class="terminal-content"></div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<br>
	<br>

</div>

<div class="modal" id="terminalModal" tabindex="-1">
    <div class="modal-dialog modal-fullscreen">
        <div class="modal-content">
            <div class="modal-body">
                <div class="terminal-container mt-4 mb-4">
		            <div class="terminal-header d-flex justify-content-between align-items-center">
		                <span class="btn btn-sm btn-danger link-unlink-button">
    						<i class="bi bi-toggle-on h6"></i>
						</span>
		                <span class="text-center flex-grow-1 fw-bold">Raw Decoys Activity</span>
		                <div class="btn-group" role="group">
		                    <button type="button" class="btn btn-sm btn-secondary minimize-button" data-bs-dismiss="modal" aria-label="Close">
		                        <i class="bi bi-dash-lg"></i>
		                    </button>
		                    <button type="button" class="btn btn-sm btn-secondary maximize-button" data-bs-dismiss="modal" aria-label="Close">
		                        <i class="bi bi-fullscreen-exit"></i>
		                    </button>
		                </div>
		            </div>
		            <div id="logListModal" class="terminal-content terminal-maximized"></div>
		        </div>
            </div>
        </div>
    </div>
</div>

	<!-- New Decoy Modal -->
	<div class="modal modal-lg fade" id="ObservableModal" tabindex="-1" aria-labelledby="ObservableModalLabel" aria-hidden="true">
	    <div class="modal-dialog modal-dialog-centered">
	        <div class="modal-content">
	            <div class="modal-header">
	                <h5 class="modal-title" id="ObservableModalLabel">Observable</h5>
	                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
	            </div>
	                <div class="modal-body">
	                    <div class="mb-3">
	                        <div class="row">
	                            <div class="col">
	                                <label class="form-label" >Decoy:</label>
									<h5 id="modalObservableDecoy"></h5>
	                            </div>
	                            <div class="col">
	                                <label class="form-label">Timestamp:</label>
									<h5 id="modalObservableTimeStamp"></h5>
								</div>
	                        </div>
							<br>
							<div class="row">
	                                <label class="form-label">Message:</label>
									<h5 id="modalObservableData"></h5>
	                        </div>
	                    </div>
	                </div>
	                <div class="modal-footer">
	                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
	                </div>
	        </div>
	    </div>
	</div>
	<!-- / New Decoy Modal -->
	
{% endblock %}